#!/usr/bin/env bash
# Generates every level-3 evidence artifact by running the checks, so nothing in them is
# typed by hand and nothing can drift from REPORT.md.
#
#   bash evidence/level-3/make-level3-checks.sh
#
# Writes: evidence/level-3/wordcount.txt
#         evidence/level-3/claim-coverage.md
#         evidence/level-3/verify.txt
#
# Re-run it after ANY edit to REPORT.md, claims/claim-map.md or sources/*.md.
# Everything below reads from disk; the only hand-written inputs are the SPEC table
# (report line -> claim id -> key#Qn) and the classification notes in the number audit.
set -u

R=REPORT.md
OUT=evidence/level-3
WC=$OUT/wordcount.txt
COV=$OUT/claim-coverage.md
VER=$OUT/verify.txt

# report line where the sentence starts | claim id | key#Qn
SPEC='
12|C3|sqlite-whentouse#Q2
14|C4|sqlite-whentouse#Q4
17|C1|duckdb-pvldb-hashjoin#Q3
20|C2|duckdb-pvldb-hashjoin#Q1
26|C5|duckdb-sigmod19#Q2
28|C20|duckdb-sigmod19#Q1
31|C6|duckdb-sigmod19#Q1
33|C7|sqlite-whentouse#Q3
38|C8|sqlite-whentouse#Q1
40|C9|sqlite-wal#Q1
42|C10|sqlite-wal#Q2
44|C11|sqlite-wal#Q3
46|C12|duckdb-sigmod19#Q3
53|C14|sqlite-cli#Q1
55|C13|duckdb-cidr20#Q1
57|C17|duckdb-cidr20#Q2
59|C18|duckdb-cidr20#Q2
61|C22|sqlite-changes#Q2
64|C23|duckdb-sigmod19#Q3
68|C24|sqlite-lts#Q1
71|C25|sqlite-lts#Q2
71|C26|sqlite-lts#Q3
74|C29|duckdb-pvldb-hashjoin#Q2
'

# --- helpers -----------------------------------------------------------------

# sentence(): the sentence that starts at line N -- consecutive lines joined with single
# spaces, up to and including the first line that ends in a full stop.
sentence() {
  awk -v n="$1" 'NR>=n { buf = (buf=="" ? $0 : buf" "$0); if ($0 ~ /\.$/) { print buf; exit } }' "$R"
}

# quote(): the verbatim quote text of <key>#<Qn>, taken from the source entry.
quote() {
  key=${1%%#*}; qn=${1##*#}
  grep -A1 "^### $qn " "sources/$key.md" | sed -n '2s/^> //p'
}

# mapfield(): field <n> of claim row <id> in claims/claim-map.md (1=id .. 7=status).
mapfield() {
  awk -F'|' -v id=" $1 " -v f="$2" '$2==id { gsub(/^ +| +$/,"",$(f+1)); print $(f+1); exit }' claims/claim-map.md
}

# hdr(): header field <name> of sources/<key>.md, quotes stripped.
hdr() {
  awk -v k="$2:" '$1==k { sub(/^[a-z_]+: */,""); gsub(/^"|"$/,""); print; exit }' "sources/$1.md"
}

# --- 1. word count -----------------------------------------------------------

{
  echo "# evidence/level-3/wordcount.txt -- generated by evidence/level-3/make-level3-checks.sh"
  echo
  echo "The canonical body word count. Body = everything before the '## Sources' heading."
  echo "Acceptance band for level 3 is 900-1200, hard, no margin."
  echo
  echo "\$ awk '/^## Sources/{exit} {print}' REPORT.md | wc -w"
  awk '/^## Sources/{exit} {print}' "$R" | wc -w
  echo
  echo "\$ grep -c '' REPORT.md"
  grep -c '' "$R"
  echo
  echo "\$ awk '/^## Sources/{exit} {print}' REPORT.md | wc -l"
  awk '/^## Sources/{exit} {print}' "$R" | wc -l
} > "$WC"

# --- 2. claim coverage table -------------------------------------------------

{
  echo "# evidence/level-3/claim-coverage.md -- generated, do not hand-edit"
  echo
  echo "Generated by \`evidence/level-3/make-level3-checks.sh\` from \`REPORT.md\` itself: every"
  echo "sentence below was **extracted from the report at the line number given**, not retyped, so"
  echo "the location and the text cannot drift apart. \`evidence/level-3/verify.txt\` §1 then greps"
  echo "each extracted sentence back against \`REPORT.md\` and prints the count."
  echo
  echo "\"Line\" is the line the sentence *starts* on; report sentences are written one per line"
  echo "(semantic line breaks), wrapped at 100 columns, so a sentence may span 2-3 physical lines."
  echo
  echo "| line | claim | key#Qn | exact sentence text in REPORT.md |"
  echo "|---|---|---|---|"
  printf '%s\n' "$SPEC" | grep -v '^$' | while IFS='|' read -r n id kq; do
    s=$(sentence "$n")
    echo "| $n | $id | \`$kq\` | $s |"
  done
  echo
  n_rows=$(printf '%s\n' "$SPEC" | grep -cv '^$')
  n_ids=$(printf '%s\n' "$SPEC" | grep -v '^$' | cut -d'|' -f2 | sort -u | wc -l | tr -d ' ')
  n_keys=$(printf '%s\n' "$SPEC" | grep -v '^$' | cut -d'|' -f3 | cut -d'#' -f1 | sort -u | wc -l | tr -d ' ')
  echo "**$n_rows rows, $n_ids distinct claim ids, $n_keys distinct source keys.** Level 3 criterion 5 asks for"
  echo "at least 12 claim rows from \`claims/claim-map.md\` to appear in the report; criterion 4 asks"
  echo "for at least 6 distinct keys cited."
  echo
  echo "Two rows share line 71: that one sentence carries both C25 (format stable, readable"
  echo "decades from now) and C26 (support intended through 2050), which are separate rows in the"
  echo "claim map resting on separate quotes (\`sqlite-lts#Q2\` and \`#Q3\`)."
  echo
  echo "## Claims restated in the recommendation"
  echo
  echo "These are the same claim rows argued a second time as decision conditions. They are **not**"
  echo "counted in the totals above; the rows above are where each claim is first asserted."
  echo
  echo "| line | claim restated | key#Qn |"
  echo "|---|---|---|"
  echo "| 90 | C8 + C10 (one writer at any instant; WAL does not lift it) | \`sqlite-whentouse#Q1\`, \`sqlite-wal#Q2\` |"
  echo "| 91 | C11 (WAL does not work over a network filesystem) | \`sqlite-wal#Q3\` |"
  echo "| 97 | C18 (single-row update efficiency is not a design goal) | \`duckdb-cidr20#Q2\` |"
  echo "| 99 | C17 (format designed for scans and bulk updates) | \`duckdb-cidr20#Q2\` |"
  echo "| 103 | C24-C26 (cross-platform file, stable format, support to 2050) | \`sqlite-lts#Q1-Q3\` |"
  echo "| 106 | C18 again, as the stated cost of choosing DuckDB | \`duckdb-cidr20#Q2\` |"
  echo "| 110 | C13 (DuckDB scanning CSV files directly) | \`duckdb-cidr20#Q1\` |"
  echo
  echo "## Claim-map rows deliberately not used"
  echo
  echo "Six of the 29 \`OK\` rows did not fit the 900-1200 word band and are absent from the report:"
  echo "C15 (import delimiters), C16 (CSV imported then sliced into summary reports), C19 (DuckDB's"
  echo "single-file design inspired by SQLite), C21 (WAL writers append rather than overwrite),"
  echo "C27 (the changelog page describes itself), C28 (a 2022 interface change held backwards"
  echo "compatible). Dropping them costs no dimension its coverage: D4 keeps C13/C14, D5 keeps"
  echo "C17/C18, D6 keeps C22/C23, D7 keeps C24/C25/C26/C29."
} > "$COV"

# --- 3. verification transcript ----------------------------------------------

{
  echo "# evidence/level-3/verify.txt -- generated by evidence/level-3/make-level3-checks.sh"
  echo "# Every command below was run by that script; the line under each is its real output."
  echo
  echo "================================================================================"
  echo "1. Each coverage row's sentence is in REPORT.md, and starts on the line claimed"
  echo "================================================================================"
  echo
  echo "For each row: (a) the extracted sentence, whitespace-collapsed, is found in the"
  echo "whitespace-collapsed report (expect 1); (b) the first 8 words of REPORT.md line N are the"
  echo "first 8 words of that sentence (expect SAME)."
  echo
  printf '%s\n' "$SPEC" | grep -v '^$' | while IFS='|' read -r n id kq; do
    s=$(sentence "$n")
    echo "--- $id  (line $n, $kq)"
    echo "\$ tr -s '[:space:]' ' ' < REPORT.md | grep -F -c \"\$(awk -v n=$n 'NR>=n{buf=(buf==\"\"?\$0:buf\" \"\$0); if (\$0 ~ /[.]\$/){print buf; exit}}' REPORT.md)\""
    c=$(tr -s '[:space:]' ' ' < "$R" | grep -F -c "$s")
    echo "$c"
    head8_line=$(sed -n "${n}p" "$R" | tr -s '[:space:]' ' ' | cut -d' ' -f1-8)
    head8_sent=$(printf '%s' "$s" | cut -d' ' -f1-8)
    if [ "$head8_line" = "$head8_sent" ]; then echo "line-start: SAME  ($head8_line ...)"; else echo "line-start: DIFFERS  line=[$head8_line] sentence=[$head8_sent]"; fi
  done
  echo
  echo "================================================================================"
  echo "2. Each coverage row resolves to an OK row in claims/claim-map.md with that key#Qn"
  echo "================================================================================"
  echo
  echo "\$ awk -F'|' -v id=' C<n> ' '\$2==id {print \$6\" | \"\$8}' claims/claim-map.md   # key#Qn | status"
  echo
  printf '%s\n' "$SPEC" | grep -v '^$' | while IFS='|' read -r n id kq; do
    mk=$(mapfield "$id" 5 | tr -d '`')
    st=$(mapfield "$id" 7)
    if [ "$mk" = "$kq" ] && [ "$st" = "OK" ]; then v=MATCH; else v="MISMATCH (map has [$mk] status [$st])"; fi
    printf '%-5s coverage=%-28s map=%-28s status=%-3s -> %s\n' "$id" "$kq" "$mk" "$st" "$v"
  done
  echo
  echo "================================================================================"
  echo "3. The claim map's verbatim fragment is inside the quote each row cites"
  echo "================================================================================"
  echo
  echo "The quote is pulled out of sources/<key>.md and the fragment grepped against THAT, not"
  echo "against the capture -- a fragment found somewhere in the document proves nothing about the"
  echo "row. Expect 1 on every line."
  echo
  printf '%s\n' "$SPEC" | grep -v '^$' | while IFS='|' read -r n id kq; do
    q=$(quote "$kq")
    f=$(mapfield "$id" 6)
    echo "\$ grep -A1 '^### ${kq##*#} ' sources/${kq%%#*}.md | sed -n '2s/^> //p' | grep -F -c \"$f\""
    printf '%s' "$q" | grep -F -c "$f"
  done
  echo
  echo "================================================================================"
  echo "4. Every [key] cited in REPORT.md exists in sources/"
  echo "================================================================================"
  echo
  echo "\$ grep -o '\\[[a-z0-9-]*\\]' REPORT.md | tr -d '[]' | sort -u"
  keys=$(grep -o '\[[a-z0-9-]*\]' "$R" | tr -d '[]' | sort -u)
  printf '%s\n' "$keys"
  echo
  echo "\$ for k in \$keys; do ls sources/\$k.md; done"
  for k in $keys; do ls "sources/$k.md"; done
  echo
  echo "\$ grep -o '\\[[a-z0-9-]*\\]' REPORT.md | tr -d '[]' | sort -u | wc -l   # distinct keys cited, need >=6"
  printf '%s\n' "$keys" | wc -l
  echo
  echo "\$ ls sources/*.md | grep -v CAPTURE_LOG | wc -l                        # entries in the dossier"
  ls sources/*.md | grep -v CAPTURE_LOG | wc -l
  echo
  echo "================================================================================"
  echo "5. The ## Sources list matches each sources/<key>.md header field for field"
  echo "================================================================================"
  echo
  echo "For each key, the report's own bullet block is cut out of REPORT.md, whitespace-collapsed,"
  echo "and each of the five header values (title, publisher, url, dated, accessed) is grepped"
  echo "against it verbatim. Expect 1 for every field of every key."
  echo
  for k in $keys; do
    blk=$(awk -v k="\`$k\`" '$0 ~ "^- \\*\\*"k { f=1; print; next } f && /^- \*\*`/ { exit } f { print }' "$R" | tr -s '[:space:]' ' ')
    echo "--- $k"
    for field in title publisher url dated accessed; do
      v=$(hdr "$k" "$field")
      c=$(printf '%s' "$blk" | grep -F -c "$v")
      printf '  %-10s %s\n     entry value: %s\n' "$field" "$c" "$v"
    done
  done
  echo
  echo "\$ grep -c '^- \\*\\*\`' REPORT.md    # bullets in ## Sources, must equal distinct keys cited"
  grep -c '^- \*\*`' "$R"
  echo
  echo "================================================================================"
  echo "6. Every number in the report body, enumerated and accounted for"
  echo "================================================================================"
  echo
  echo "Not a pattern grep for smuggled figures -- a pattern grep only proves the pattern. EVERY"
  echo "numeric token in the body is pulled out with its line and given a class; the residual is"
  echo "printed at the end rather than assumed empty."
  echo
  echo "6a. Raw enumeration, nothing removed. Citation keys (duckdb-sigmod19, duckdb-cidr20) and"
  echo "    inline code spans (\`sqlite3\`) contain digits, so they appear here too and are"
  echo "    classified as such below rather than being quietly filtered out."
  echo
  echo "\$ awk '/^## Sources/{exit} {n=\$0; while (match(n,/[0-9]+([.][0-9]+)*/)) { print NR\": \"substr(n,RSTART,RLENGTH); n=substr(n,RSTART+RLENGTH) }}' REPORT.md"
  awk '/^## Sources/{exit} {n=$0; while (match(n,/[0-9]+([.][0-9]+)*/)) { print NR": "substr(n,RSTART,RLENGTH); n=substr(n,RSTART+RLENGTH) }}' "$R"
  echo
  echo "\$ ... | wc -l    # total numeric tokens in the body"
  awk '/^## Sources/{exit} {n=$0; while (match(n,/[0-9]+([.][0-9]+)*/)) { print NR": "substr(n,RSTART,RLENGTH); n=substr(n,RSTART+RLENGTH) }}' "$R" | wc -l
  echo
  echo "6b. Same enumeration, one class per token. SOURCED-* names the quote, locator or header"
  echo "    field that accounts for the token; NOT-A-QUANTITY names a token that is part of a"
  echo "    citation key, a code span or this report's own list numbering; RESIDUAL is a number in"
  echo "    prose that no source accounts for. UNCLASSIFIED must not occur."
  echo
  awk '/^## Sources/{exit} { line=NR; n=$0;
        while (match(n,/[0-9]+([.][0-9]+)*/)) {
          t = substr(n,RSTART,RLENGTH); pre = substr(n,1,RSTART-1); n = substr(n,RSTART+RLENGTH);
          c = "UNCLASSIFIED";
          if (t=="19" && pre ~ /duckdb-sigmod$/)      c="NOT-A-QUANTITY: digits of the citation key duckdb-sigmod19";
          else if (t=="20" && pre ~ /duckdb-cidr$/)   c="NOT-A-QUANTITY: digits of the citation key duckdb-cidr20";
          else if (t=="3"  && pre ~ /sqlite$/)        c="NOT-A-QUANTITY: the shell name sqlite3, in sqlite-whentouse#Q3";
          else if (t=="2019")                         c="SOURCED: dated 2019-06-30 / publisher of sources/duckdb-sigmod19.md";
          else if (t=="2020" && line==61)             c="SOURCED: sqlite-changes#Q2 locator, release entry 2020-08-14 (3.33.0)";
          else if (t=="2020")                         c="SOURCED: dated 2020-01-12 / publisher of sources/duckdb-cidr20.md";
          else if (t=="3.33.0")                       c="SOURCED: sqlite-changes#Q2 locator, release entry 2020-08-14 (3.33.0)";
          else if (t=="2025")                         c="SOURCED: dated 2025 of sources/duckdb-pvldb-hashjoin.md";
          else if (t=="32" || t=="64")                c="SOURCED: sqlite-lts#Q1, bit-for-bit identical on 32-bit, 64-bit ...";
          else if (t=="2050")                         c="SOURCED: sqlite-lts#Q3, support SQLite through the year 2050";
          else if (t=="1.2.0")                        c="SOURCED: duckdb-pvldb-hashjoin#Q2, available in the v1.2.0 release";
          else if (t=="5")                            c="RESIDUAL: the reader'\''s own ~5 GB, the workload the task names";
          else if (line==84 && (t=="2"||t=="4"))      c="NOT-A-QUANTITY: cross-reference to conditions 2-4 of this report";
          else if (t ~ /^[1-4]$/ && line ~ /^(83|89|95|101)$/) c="NOT-A-QUANTITY: this report'\''s own numbered condition heading";
          printf "  line %-4s %-8s %s\n", line, t, c;
        } }' "$R"
  echo
  echo "\$ ... | grep -c UNCLASSIFIED     (must be 0)"
  awk '/^## Sources/{exit} { line=NR; n=$0;
        while (match(n,/[0-9]+([.][0-9]+)*/)) {
          t = substr(n,RSTART,RLENGTH); pre = substr(n,1,RSTART-1); n = substr(n,RSTART+RLENGTH);
          c = "UNCLASSIFIED";
          if (t=="19" && pre ~ /duckdb-sigmod$/) c="k"; else if (t=="20" && pre ~ /duckdb-cidr$/) c="k";
          else if (t=="3" && pre ~ /sqlite$/) c="k";
          else if (t=="2019"||t=="2020"||t=="3.33.0"||t=="2025"||t=="32"||t=="64"||t=="2050"||t=="1.2.0") c="s";
          else if (t=="5") c="r";
          else if (line==84 && (t=="2"||t=="4")) c="k";
          else if (t ~ /^[1-4]$/ && (line==83||line==89||line==95||line==101)) c="k";
          print c; } }' "$R" | grep -c UNCLASSIFIED
  echo
  echo "\$ ... | grep -c RESIDUAL         (7: the seven occurrences of the reader's own 5 GB)"
  awk '/^## Sources/{exit} { line=NR; n=$0;
        while (match(n,/[0-9]+([.][0-9]+)*/)) {
          t = substr(n,RSTART,RLENGTH); n = substr(n,RSTART+RLENGTH);
          if (t=="5") print "RESIDUAL"; } }' "$R" | grep -c RESIDUAL
  echo
  echo "The residual is one number: 5, as in \"~5 GB\", the dataset size the task itself specifies."
  echo "It is the reader's input to the decision, not a claim about SQLite or DuckDB, and the"
  echo "report never derives anything from it -- no ratio against the terabyte bound in"
  echo "sqlite-whentouse#Q4, which is exactly the arithmetic that failed level 2 on first judging."
  echo
  echo "That table is the check; the greps below are a second, independent net over the same body."
  echo "The unit alternatives are anchored on a non-letter so that '2019 sentence' is not read as"
  echo "'2019 s' -- the first cut of this grep matched exactly that and printed 1."
  echo
  echo "\$ awk '/^## Sources/{exit} {print}' REPORT.md | grep -E -c -i '[0-9]+ *(x|times) (faster|slower)|[0-9]+ *(ms|s|sec|seconds|MB/s|GB/s)([^a-z]|\$)|orders of magnitude|[0-9]+ *%'"
  awk '/^## Sources/{exit} {print}' "$R" | grep -E -c -i '[0-9]+ *(x|times) (faster|slower)|[0-9]+ *(ms|s|sec|seconds|MB/s|GB/s)([^a-z]|$)|orders of magnitude|[0-9]+ *%'
  echo "(0: no timing, no multiplier, no percentage, no derived ratio.)"
  echo
  echo "\$ awk '/^## Sources/{exit} {print}' REPORT.md | grep -E -c -i 'faster|slower|speedup|throughput of|benchmark(ed)? (shows|show|proves)'"
  awk '/^## Sources/{exit} {print}' "$R" | grep -E -c -i 'faster|slower|speedup|throughput of|benchmark(ed)? (shows|show|proves)'
  echo "(0: the report makes no comparative speed statement at all.)"
  echo
  echo "================================================================================"
  echo "7. Nothing was built, run or benchmarked"
  echo "================================================================================"
  echo
  echo "\$ git status --porcelain"
  git status --porcelain
  echo
  echo "\$ git status --porcelain | awk '{print \$NF}' | grep -E -c '[.](db|sqlite|sqlite3|duckdb|wal|shm|parquet|csv|py|c|h|sql)\$'"
  git status --porcelain | awk '{print $NF}' | grep -E -c '[.](db|sqlite|sqlite3|duckdb|wal|shm|parquet|csv|py|c|h|sql)$'
  echo "(0 expected: no database file, no data file, no program source.)"
  echo
  echo "\$ ls sources/raw/ | wc -l    # captures untouched this level"
  ls sources/raw/ | wc -l
  echo
  echo "--- generated $(date -u '+%Y-%m-%dT%H:%M:%SZ') by evidence/level-3/make-level3-checks.sh"
} > "$VER"

echo "wrote $WC $COV $VER"
