// The Karpathy-style wiki memory: a folder of markdown pages with frontmatter,
// an index the harness regenerates, and an append-only log. Agents write pages
// themselves (their prompts explain when); the harness only keeps the index
// honest and renders it into prompts.

import fs from "node:fs";
import path from "node:path";

export interface MemoryPage {
  file: string;
  name: string;
  description: string;
  tags: string[];
  chars: number;
  modified_at: number;
}

const INDEX_HEADER = `# Memory index

One line per page, regenerated by the harness after every agent session. Pages are
markdown files in this folder with YAML frontmatter (\`name\`, \`description\`, \`tags\`).
Append dated one-liners to \`log.md\` when you add or change a page.

`;

export function ensureMemoryDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
  const index = path.join(dir, "index.md");
  if (!fs.existsSync(index)) fs.writeFileSync(index, `${INDEX_HEADER}(no pages yet)\n`, "utf-8");
  const log = path.join(dir, "log.md");
  if (!fs.existsSync(log)) fs.writeFileSync(log, "# Memory log\n\n", "utf-8");
}

function parseFrontmatter(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!text.startsWith("---")) return out;
  const end = text.indexOf("\n---", 3);
  if (end < 0) return out;
  const block = text.slice(3, end);
  for (const line of block.split("\n")) {
    const match = /^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$/.exec(line.trim());
    if (match) out[match[1]!] = match[2]!.trim().replace(/^["']|["']$/g, "");
  }
  return out;
}

export function listMemoryPages(dir: string): MemoryPage[] {
  let entries: string[];
  try {
    entries = fs.readdirSync(dir);
  } catch {
    return [];
  }
  const pages: MemoryPage[] = [];
  for (const entry of entries.sort()) {
    if (!entry.endsWith(".md") || entry === "index.md" || entry === "log.md") continue;
    const file = path.join(dir, entry);
    let stat: fs.Stats;
    try {
      stat = fs.statSync(file);
    } catch {
      continue;
    }
    if (!stat.isFile() || stat.size > 512 * 1024) continue;
    const text = fs.readFileSync(file, "utf-8");
    const meta = parseFrontmatter(text);
    const firstHeading = /^#\s+(.+)$/m.exec(text)?.[1]?.trim() ?? "";
    const firstParagraph = text
      .replace(/^---[\s\S]*?\n---\n?/, "")
      .split(/\n\s*\n/)
      .map((chunk) => chunk.trim())
      .find((chunk) => chunk && !chunk.startsWith("#")) ?? "";
    pages.push({
      file: entry,
      name: meta.name || firstHeading || entry.replace(/\.md$/, ""),
      description: meta.description || firstParagraph.replace(/\s+/g, " ").slice(0, 200),
      tags: (meta.tags || "")
        .replace(/^\[|\]$/g, "")
        .split(",")
        .map((tag) => tag.trim())
        .filter((tag) => tag),
      chars: text.length,
      modified_at: stat.mtimeMs / 1000,
    });
  }
  return pages;
}

/** Rewrite index.md from the pages on disk (idempotent). */
export function regenerateMemoryIndex(dir: string): MemoryPage[] {
  ensureMemoryDir(dir);
  const pages = listMemoryPages(dir);
  const lines = pages.map(
    (page) => `- [${page.name}](${page.file}) — ${page.description}${page.tags.length ? ` (${page.tags.join(", ")})` : ""}`,
  );
  fs.writeFileSync(path.join(dir, "index.md"), `${INDEX_HEADER}${lines.length ? lines.join("\n") : "(no pages yet)"}\n`, "utf-8");
  return pages;
}

/** The index as prompt text, bounded. */
export function memoryIndexText(dir: string, maxChars = 6000): string {
  const pages = listMemoryPages(dir);
  if (!pages.length) return "(the memory wiki is empty)";
  const lines = pages.map((page) => `- ${page.name} (${page.file}): ${page.description}`);
  const text = lines.join("\n");
  return text.length > maxChars ? `${text.slice(0, maxChars)}\n[index truncated; read index.md for the rest]` : text;
}

export function appendMemoryLog(dir: string, line: string): void {
  ensureMemoryDir(dir);
  const stamp = new Date().toISOString().slice(0, 16).replace("T", " ");
  fs.appendFileSync(path.join(dir, "log.md"), `- ${stamp} — ${line.trim()}\n`, "utf-8");
}
