// Ported 1:1 from LongHorizon-Harness tests/test_role_prompts.py
//
// Every assertion of the Python test module is reproduced below, plus
// golden-snapshot tests whose expected files were generated by running the
// PYTHON originals (see tests/golden/*.txt and tests/golden/parser_cases.json).

import { readFileSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";

import {
  AUDITOR_CONTRACT_BACKCHECK,
  TASK_CONTRACT_RULES,
  normalizePromptLanguage,
} from "../src/prompt_texts.js";
import type { PromptLanguage } from "../src/prompt_texts.js";
import {
  MANAGER_NEXT_CLI,
  MANAGER_NEXT_DONE,
  buildRoleAuditorFormatRepairPrompt,
  buildRoleAuditorPrompt,
  buildRoleExecutorPrompt,
  buildRoleFinalResponsePrompt,
  buildRoleManagerPrompt,
  clipPreserve,
  extractRelatedReportRefs,
  extractRoleManagerAnswerChoices,
  extractRoleManagerPlanText,
  extractRoleManagerQuestion,
  extractRoleTaskContract,
  extractRoleTaskState,
  formatAuditFindings,
  formatHarnessFeedbackContext,
  formatManagementHistory,
  formatRelatedAuditorReports,
  formatVerifiedIntermediateContext,
  parseRoleManagerNextStep,
  roundRefToIndex,
} from "../src/role_prompts.js";
import type { ManagedRoundLike } from "../src/role_prompts.js";

const LANGUAGES: PromptLanguage[] = ["en"];

function goldenPath(name: string): URL {
  return new URL(`./golden/${name}`, import.meta.url);
}

function readGolden(name: string): string {
  return readFileSync(goldenPath(name), "utf8");
}

interface GoldenInputs {
  rounds: ManagedRoundLike[];
  manager: {
    task: string;
    round_index: number;
    task_state: string;
    task_contract: string;
    round_budget: number;
    max_history_chars: number;
  };
  executor: {
    task: string;
    plan_text: string;
    next_step: "gui" | "cli";
    task_state: string;
    task_contract: string;
    related_auditor_reports: string;
    workspace_path: string;
  };
  executor_gui: GoldenInputs["executor"];
  auditor: GoldenInputs["executor"] & {
    executor_output: string;
    max_executor_output_chars: number;
  };
  auditor_gui: GoldenInputs["auditor"];
  format_repair: { report_text: string };
  format_repair_empty: { report_text: string };
  final_response: {
    task: string;
    status: string;
    abort_reason: string;
    task_state: string;
    operator_instructions: string;
    max_evidence_chars: number;
    max_deliverable_chars: number;
  };
}

const inputs = JSON.parse(readGolden("inputs.json")) as GoldenInputs;

// ---------------------------------------------------------------------------
// Ported from tests/test_role_prompts.py
// ---------------------------------------------------------------------------

for (const language of LANGUAGES) {
  test(`auditor prompt does not turn unobservable history into a blocker [${language}]`, () => {
    const contractRules = TASK_CONTRACT_RULES[language];
    const auditRules = AUDITOR_CONTRACT_BACKCHECK[language];

    assert.ok(contractRules.includes("does not silently become a historical guarantee"));
    assert.ok(auditRules.includes("missing full executor transcript is not by itself evidence"));
    assert.ok(
      auditRules.includes("unobservable historical negative is non-blocking residual risk"),
    );
    assert.ok(auditRules.includes("Do not request a repeat solely"));
  });

  test(`final response prompt preserves operator follow-up [${language}]`, () => {
    const prompt = buildRoleFinalResponsePrompt({
      task: "Create the requested file.",
      rounds: [],
      status: "complete",
      abortReason: "",
      taskState: "The file was independently verified.",
      operatorInstructions: "The final reply must contain OPERATOR_MARKER.",
      language,
    });

    assert.ok(prompt.includes("OPERATOR_MARKER"));
    assert.ok(prompt.includes("Authoritative operator follow-up instructions"));
  });

  test(`final response prompt includes verified executor deliverable [${language}]`, () => {
    const marker = "https://example.test/source METRIC=405K";
    const prompt = buildRoleFinalResponsePrompt({
      task: "Return the researched report with its citations.",
      rounds: [
        {
          round_index: 1,
          next_step: MANAGER_NEXT_CLI,
          plan_text: "research",
          executor_output: marker,
          auditor_report: "Status: complete\nIntegrity: clean\nContract audit: aligned",
        },
      ],
      status: "complete",
      abortReason: "",
      taskState: "The report was verified.",
      language,
    });

    assert.ok(prompt.includes(marker));
    assert.ok(prompt.includes("preserve every source, citation, figure"));
  });
}

for (const line of [
  "Next: done — all constraints passed",
  "Next: done -- all constraints passed",
]) {
  test(`manager route accepts delimited rationale [${line}]`, () => {
    assert.equal(parseRoleManagerNextStep(line), MANAGER_NEXT_DONE);
  });
}

test("manager route rejects undelimited suffix", () => {
  assert.notEqual(parseRoleManagerNextStep("Next: done later"), MANAGER_NEXT_DONE);
});

for (const language of LANGUAGES) {
  test(`manager prompt exposes total and remaining round budget [${language}]`, () => {
    const prompt = buildRoleManagerPrompt({
      task: "Research and compare the sources.",
      rounds: [],
      roundIndex: 3,
      roundBudget: 10,
      language,
    });

    assert.ok(prompt.includes("Configured round limit: 10"));
    assert.ok(prompt.includes("Rounds remaining, including this one: 8"));
    assert.ok(prompt.includes("do not schedule a prerequisite-only subtask"));
  });
}

test("role prompts distinguish workspace from run records", () => {
  const executor = buildRoleExecutorPrompt({
    task: "create a report",
    planText: "write report.md",
    nextStep: MANAGER_NEXT_CLI,
    workspacePath: "/tmp/workspace",
  });
  const auditor = buildRoleAuditorPrompt({
    task: "create a report",
    planText: "write report.md",
    executorOutput: "done",
    nextStep: MANAGER_NEXT_CLI,
    workspacePath: "/tmp/workspace",
  });

  assert.ok(executor.includes("Workspace root: /tmp/workspace"));
  assert.ok(executor.includes("run-record directory"));
  assert.ok(auditor.includes("Real workspace root: /tmp/workspace"));
  assert.ok(auditor.includes("Executor text is only a claim"));
  assert.ok(auditor.includes("not require every subtask to create a file"));
  assert.ok(auditor.includes("Private Dashboard trajectory images"));
  assert.ok(!auditor.includes(".longhorizon-evidence"));
});

// ---------------------------------------------------------------------------
// Language switch
// ---------------------------------------------------------------------------

test("normalizePromptLanguage mirrors the Python normalizer", () => {
  assert.equal(normalizePromptLanguage("en"), "en");
  assert.equal(normalizePromptLanguage(""), "en");
  assert.equal(normalizePromptLanguage(null), "en");
  assert.equal(normalizePromptLanguage(undefined), "en");
  assert.throws(
    () => normalizePromptLanguage("fr"),
    (error: Error) =>
      error.message === "Unsupported prompt language: 'fr'; expected 'en'.",
  );
});

// ---------------------------------------------------------------------------
// Golden snapshots of the six builders, generated from the Python originals
// ---------------------------------------------------------------------------

for (const language of LANGUAGES) {
  test(`golden: build_role_manager_prompt [${language}]`, () => {
    const m = inputs.manager;
    assert.equal(
      buildRoleManagerPrompt({
        task: m.task,
        rounds: inputs.rounds,
        roundIndex: m.round_index,
        taskState: m.task_state,
        taskContract: m.task_contract,
        roundBudget: m.round_budget,
        language,
        maxHistoryChars: m.max_history_chars,
      }),
      readGolden(`manager.${language}.txt`),
    );
  });

  for (const [name, fixture] of [
    ["executor_cli", inputs.executor],
    ["executor_gui", inputs.executor_gui],
  ] as const) {
    test(`golden: build_role_executor_prompt ${name} [${language}]`, () => {
      assert.equal(
        buildRoleExecutorPrompt({
          task: fixture.task,
          planText: fixture.plan_text,
          nextStep: fixture.next_step,
          taskState: fixture.task_state,
          taskContract: fixture.task_contract,
          relatedAuditorReports: fixture.related_auditor_reports,
          workspacePath: fixture.workspace_path,
          language,
        }),
        readGolden(`${name}.${language}.txt`),
      );
    });
  }

  for (const [name, fixture] of [
    ["auditor_cli", inputs.auditor],
    ["auditor_gui", inputs.auditor_gui],
  ] as const) {
    test(`golden: build_role_auditor_prompt ${name} [${language}]`, () => {
      assert.equal(
        buildRoleAuditorPrompt({
          task: fixture.task,
          planText: fixture.plan_text,
          executorOutput: fixture.executor_output,
          nextStep: fixture.next_step,
          taskState: fixture.task_state,
          taskContract: fixture.task_contract,
          relatedAuditorReports: fixture.related_auditor_reports,
          workspacePath: fixture.workspace_path,
          maxExecutorOutputChars: fixture.max_executor_output_chars,
          language,
        }),
        readGolden(`${name}.${language}.txt`),
      );
    });
  }

  for (const [name, fixture] of [
    ["format_repair", inputs.format_repair],
    ["format_repair_empty", inputs.format_repair_empty],
  ] as const) {
    test(`golden: build_role_auditor_format_repair_prompt ${name} [${language}]`, () => {
      assert.equal(
        buildRoleAuditorFormatRepairPrompt({ reportText: fixture.report_text, language }),
        readGolden(`${name}.${language}.txt`),
      );
    });
  }

  test(`golden: build_role_final_response_prompt [${language}]`, () => {
    const f = inputs.final_response;
    assert.equal(
      buildRoleFinalResponsePrompt({
        task: f.task,
        rounds: inputs.rounds,
        status: f.status,
        abortReason: f.abort_reason,
        taskState: f.task_state,
        operatorInstructions: f.operator_instructions,
        language,
        maxEvidenceChars: f.max_evidence_chars,
        maxDeliverableChars: f.max_deliverable_chars,
      }),
      readGolden(`final_response.${language}.txt`),
    );
  });
}

// ---------------------------------------------------------------------------
// Golden parser/formatter cases, generated from the Python originals
// ---------------------------------------------------------------------------

interface ParserCase {
  fn: string;
  args: unknown[];
  kwargs: Record<string, unknown>;
  expected: unknown;
}

const parserCases = JSON.parse(readGolden("parser_cases.json")) as ParserCase[];

type Dispatcher = (args: unknown[], kwargs: Record<string, unknown>) => unknown;

const dispatch: Record<string, Dispatcher> = {
  parse_role_manager_next_step: (a) => parseRoleManagerNextStep(a[0] as string),
  extract_role_manager_plan_text: (a) => extractRoleManagerPlanText(a[0] as string),
  extract_role_task_state: (a, k) =>
    extractRoleTaskState(a[0] as string, { fallback: k["fallback"] as string | undefined }),
  extract_role_task_contract: (a, k) =>
    extractRoleTaskContract(a[0] as string, { fallback: k["fallback"] as string | undefined }),
  extract_related_report_refs: (a) => extractRelatedReportRefs(a[0] as string),
  extract_role_manager_question: (a) => extractRoleManagerQuestion(a[0] as string),
  extract_role_manager_answer_choices: (a) => extractRoleManagerAnswerChoices(a[0] as string),
  _round_ref_to_index: (a) => roundRefToIndex(a[0] as string),
  _clip_preserve: (a) => clipPreserve(a[0] as string, a[1] as number),
  format_verified_intermediate_context: (a, k) =>
    formatVerifiedIntermediateContext(a[0] as ManagedRoundLike[], {
      maxChars: k["max_chars"] as number | undefined,
      language: k["language"] as string | undefined,
    }),
  format_related_auditor_reports: (a, k) =>
    formatRelatedAuditorReports(a[0] as ManagedRoundLike[], a[1] as string[], {
      maxChars: k["max_chars"] as number | undefined,
      language: k["language"] as string | undefined,
    }),
  format_harness_feedback_context: (a, k) =>
    formatHarnessFeedbackContext(a[0] as ManagedRoundLike[], {
      maxChars: k["max_chars"] as number | undefined,
    }),
  format_audit_findings: (a, k) =>
    formatAuditFindings(a[0] as ManagedRoundLike[], {
      maxChars: k["max_chars"] as number | undefined,
      language: k["language"] as string | undefined,
    }),
  format_management_history: (a, k) =>
    formatManagementHistory(a[0] as ManagedRoundLike[], {
      includeEmpty: k["include_empty"] as boolean | undefined,
      maxChars: k["max_chars"] as number | undefined,
    }),
};

parserCases.forEach((testCase, index) => {
  test(`golden parser case ${index}: ${testCase.fn}`, () => {
    const handler = dispatch[testCase.fn];
    assert.ok(handler, `no dispatcher for ${testCase.fn}`);
    const args = testCase.args.map((arg) => (arg === "__ROUNDS__" ? inputs.rounds : arg));
    assert.deepEqual(handler(args, testCase.kwargs), testCase.expected);
  });
});
